version: "3"

services:
  server:
    build:
      context: .
    environment:
      NODE_ENV: test
    ports:
      - "3000:3000"
    networks:
      - red
    volumes:
      - ./:/app
    depends_on:
      - db

  db:
    image: mysql:8.3.0
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    ports:
      - "3306:3306"
    networks:
      - red

networks:
  red:
    driver: bridge
